### ISSUE TITLE
Error when viewing handouts

### ISSUE THREAD

**Issue by gregersn** [gregersn/whathappened#545]
```
[2022-12-03 17:13:48,366] ERROR in app: Exception on /campaign/2/handouts/21/ [GET]
Traceback (most recent call last):
  File "/home/whathappened/.venv/lib/python3.10/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/whathappened/.venv/lib/python3.10/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/whathappened/.venv/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/whathappened/.venv/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/whathappened/.venv/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/whathappened/.venv/lib/python3.10/site-packages/whathappened/campaign/views.py", line 43, in dispatch_request
    return self.view(campaign_id, handout_id)
  File "/home/whathappened/.venv/lib/python3.10/site-packages/whathappened/campaign/views.py", line 131, in view
    return render_template('campaign/handout.html.jinja',
  File "/home/whathappened/.venv/lib/python3.10/site-packages/flask/templating.py", line 147, in render_template
    return _render(app, template, context)
  File "/home/whathappened/.venv/lib/python3.10/site-packages/flask/templating.py", line 130, in _render
    rv = template.render(context)
  File "/home/whathappened/.venv/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/whathappened/.venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/whathappened/.venv/lib/python3.10/site-packages/whathappened/templates/campaign/handout.html.jinja", line 1, in top-level template code
    {% extends 'base.html.jinja' %}
  File "/home/whathappened/.venv/lib/python3.10/site-packages/whathappened/templates/base.html.jinja", line 1, in top-level template code
    {% extends 'shell.html.jinja' %}
  File "/home/whathappened/.venv/lib/python3.10/site-packages/whathappened/templates/shell.html.jinja", line 12, in top-level template code
    {% block body %}
  File "/home/whathappened/.venv/lib/python3.10/site-packages/whathappened/templates/base.html.jinja", line 50, in block 'body'
    {% block content %}{% endblock %}
  File "/home/whathappened/.venv/lib/python3.10/site-packages/whathappened/templates/campaign/handout.html.jinja", line 46, in block 'content'
    <div>{{ assetsform.asset(class_="asset-selector") }}</div>
  File "/home/whathappened/.venv/lib/python3.10/site-packages/wtforms/fields/core.py", line 172, in __call__
    return self.meta.render_field(self, kwargs)
  File "/home/whathappened/.venv/lib/python3.10/site-packages/wtforms/meta.py", line 64, in render_field
    return field.widget(field, **render_kw)
  File "/home/whathappened/.venv/lib/python3.10/site-packages/wtforms/widgets/core.py", line 351, in __call__
    for val, label, selected in field.iter_choices():
  File "/home/whathappened/.venv/lib/python3.10/site-packages/whathappened/forms/fields/alchemy.py", line 129, in iter_choices
    yield (pk, self.get_label(obj), obj == self.data)
  File "/home/whathappened/.venv/lib/python3.10/site-packages/whathappened/userassets/forms.py", line 41, in <lambda>
    get_label=lambda x: "/".join(x.path.split('/')[2:]),
AttributeError: 'PosixPath' object has no attribute 'split'
```

**Comment by gregersn** [comment]
Fixed in https://github.com/gregersn/whathappened/pull/546
